# Generated by Django 4.0.1 on 2022-02-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydb',
            name='img',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
