# Generated by Django 4.0.1 on 2022-02-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_companydb_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydb',
            old_name='img',
            new_name='abc',
        ),
    ]
